Models/Invoice/Invoice_Close_Data.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
namespace TNStores
{
    public class Invoice_Close_Data
    {
        public static List<Invoice_Close_Model> List(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = "SELECT * FROM FNC_Invoice_Close WHERE RecordStatus != 99 AND PartnerNumber = @PartnerNumber ";
            string zConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Invoice_Close_Model> zList = new List<Invoice_Close_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Invoice_Close_Model()
                {
                    CloseKey = r["CloseKey"].ToString(),
                    CloseDate = r["CloseDate"].ToString(),
                    CloseType = r["CloseType"].ToString(),
                    CloseAmount = r["CloseAmount"].ToDouble(),
                    Description = r["Description"].ToString(),
                    JsonData = r["JsonData"].ToString(),
                    RecordStatus = r["RecordStatus"].ToInt(),
                    PartnerNumber = r["PartnerNumber"].ToString(),
                    CreatedOn = (r["CreatedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["CreatedOn"]),
                    CreatedBy = r["CreatedBy"].ToString(),
                    CreatedName = r["CreatedName"].ToString(),
                    ModifiedOn = (r["ModifiedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["ModifiedOn"]),
                    ModifiedBy = r["ModifiedBy"].ToString(),
                    ModifiedName = r["ModifiedName"].ToString(),
                });
            }
            return zList;
        }
    }
}

Models/Invoice/Invoice_Close_Model.cs
using System;
namespace TNStores
{
    public class Invoice_Close_Model
    {
        #region [ Field Name ]
        private string _CloseKey = "";
        private string _CloseDate = "";
        private string _CloseType = "";
        private double _CloseAmount = 0;
        private string _Description = "";
        private string _JsonData = "";
        private int _RecordStatus = 0;
        private string _PartnerNumber = "";
        private DateTime _CreatedOn = DateTime.MinValue;
        private string _CreatedBy = "";
        private string _CreatedName = "";
        private DateTime _ModifiedOn = DateTime.MinValue;
        private string _ModifiedBy = "";
        private string _ModifiedName = "";
        #endregion

        #region [ Properties ]
        public string CloseKey
        {
            get { return _CloseKey; }
            set { _CloseKey = value; }
        }
        public string CloseDate
        {
            get { return _CloseDate; }
            set { _CloseDate = value; }
        }
        public string CloseType
        {
            get { return _CloseType; }
            set { _CloseType = value; }
        }
        public double CloseAmount
        {
            get { return _CloseAmount; }
            set { _CloseAmount = value; }
        }
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }
        public string JsonData
        {
            get { return _JsonData; }
            set { _JsonData = value; }
        }
        public int RecordStatus
        {
            get { return _RecordStatus; }
            set { _RecordStatus = value; }
        }
        public string PartnerNumber
        {
            get { return _PartnerNumber; }
            set { _PartnerNumber = value; }
        }
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { _CreatedOn = value; }
        }
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set { _CreatedBy = value; }
        }
        public string CreatedName
        {
            get { return _CreatedName; }
            set { _CreatedName = value; }
        }
        public DateTime ModifiedOn
        {
            get { return _ModifiedOn; }
            set { _ModifiedOn = value; }
        }
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set { _ModifiedBy = value; }
        }
        public string ModifiedName
        {
            get { return _ModifiedName; }
            set { _ModifiedName = value; }
        }
        #endregion
    }
}

Models/Invoice/Invoice_Quarter_Model.cs
namespace TNStores
{
    public class Invoice_Quarter_Model
    {
        public int Previous { get; set; } = 0;  //Số quý trước
        public int Current { get; set; } = 0;      //Số quý hiện tại
        public double AmountPrevious { get; set; } = 0; //Số tiền quý trước
        public double IncomeWithV { get; set; } = 0;  //Doanh số bán ra chịu thuế
        public double IncomeNoV { get; set; } = 0; //Doanh số bán ra không chịu thuế
        public double InComeTotal { get; set; } = 0;  //Tổng doanh số bán ra
        public double AmountVatInTotal { get; set; } = 0;    //Thuế GTGT đầu vào Q4
        public double AmountVatInDirect { get; set; } = 0;    //   -  Số V đầu vào trực tiếp
        public double AmountVatInShare { get; set; } = 0;     //   -  Số V đầu vào dùng chung
        public double AmountVatInShareToMinus { get; set; } = 0;     //Số V dc khấu trừ của hóa đơn dùng chung
        public double AmountVatAllowMinus { get; set; } = 0;   //Tổng số V được trừ trong quý
        public double AmountVatOutTotal { get; set; } = 0; //Thuế GTGT đầu ra Q4
        public double AmountPayCurrent { get; set; } = 0; //Số tiền nộp thuế của quý hiện tại
        public double AmountPayInclude { get; set; } = 0; //Số tiền nộp thuế khi cộng quý trước
        public double AmountNext { get; set; } = 0;   //Số tiền chuyển tiếp qua quý kế tiếp
    }
}

Controllers/FinancialController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace TNStores.Controllers
{
    public class FinancialController : BaseController
    {
        //--------------------------------------------------------------------------------------------------------------------------------------------- INVOICE

        #region [Danh sách hđ vào]
        public ActionResult ListInvoiceIN()
        {
            DateTime zFromDate = DateTime.Now;
            DateTime zToDate = DateTime.Now;
            zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, 1, 0, 0, 0);
            zToDate = zFromDate.AddMonths(1).AddDays(-1);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);

            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message, zFromDate, zToDate, "", "IN");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceIN = ListInvoice;
            ViewBag.DateView = zFromDate.ToString("dd/MM") + " - " + zToDate.ToString("dd/MM") + " /" + zFromDate.ToString("yyyy");
            return View("~/Views/Desktop/Financial/Invoice/IN.cshtml");
        }
        /// <summary>
        /// Tim theo tùy chọn từ ngày đến ngày
        /// </summary>
        /// <param name="FromDate"></param>
        /// <param name="ToDate"></param>
        /// <param name="SearchID"></param>
        /// <returns></returns>
        public ActionResult SearchInvoiceIN_Date(string FromDate = "", string ToDate = "")
        {
            DateTime zFromDate = DateTime.Now;
            if (FromDate.Length > 0)
            {
                DateTime.TryParseExact(FromDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zFromDate);
            }

            DateTime zToDate = DateTime.Now;
            if (ToDate.Length > 0)
            {
                DateTime.TryParseExact(ToDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zToDate);
            }

            zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, zFromDate.Day, 0, 0, 0);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);

            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message, zFromDate, zToDate, "", "IN");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceIN = ListInvoice;
            ViewBag.DateView = zFromDate.ToString("dd/MM") + " - " + zToDate.ToString("dd/MM") + " /" + zFromDate.ToString("yyyy");

            return View("~/Views/Desktop/Financial/Invoice/IN.cshtml");
        }
        /// <summary>
        /// Tìm theo button tới lui QUÝ
        /// </summary>
        /// <param name="btnAction"></param>
        /// <param name="DateView"></param>
        /// <returns></returns>
        public ActionResult SearchInvoiceIN_Button(string btnAction = "", string DateView = "")
        {
            #region Datetime string to fromdate - todate
            int Month = DateTime.Now.Month;
            int Year = DateTime.Now.Year;
            if (DateView != string.Empty)
            {
                Month = DateView.Split('/')[0].ToInt();
                Year = DateView.Split('/')[1].ToInt();

                if (Year.ToString().Length < 4)
                {
                    Month = DateTime.Now.Month;
                    Year = DateTime.Now.Year;
                }
            }
            switch (btnAction)
            {
                case "btn_Prev":
                    Month = Month - 1;
                    break;
                case "btn_Next":
                    Month = Month + 1;
                    break;
            }
            if (Month <= 0)
            {
                Month = 12;
                Year = Year - 1;
            }
            if (Month >= 13)
            {
                Month = 1;
                Year = Year + 1;
            }
            DateTime zDateView = DateTime.Now;
            zDateView = new DateTime(Year, Month, 1, 23, 59, 59);
            DateTime zFromDate = new DateTime(zDateView.Year, zDateView.Month, 1, 0, 0, 0);
            DateTime zToDate = zFromDate.AddMonths(1).AddDays(-1);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);
            #endregion
            ViewBag.DateView = Month + "/" + Year;
            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message, zFromDate, zToDate, "", "IN");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceIN = ListInvoice;
            return View("~/Views/Desktop/Financial/Invoice/IN.cshtml");
        }
        #endregion

        #region [Danh sách hđ ra]
        public ActionResult ListInvoiceOUT()
        {
            DateTime zFromDate = DateTime.Now;
            DateTime zToDate = DateTime.Now;
            zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, 1, 0, 0, 0);
            zToDate = zFromDate.AddMonths(1).AddDays(-1);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);

            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message1, zFromDate, zToDate, "", "OUT");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceOUT = ListInvoice;
            ViewBag.ListInvoiceIN = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message2, zFromDate, zToDate, "", "IN");
            ViewBag.DateView = zFromDate.ToString("dd/MM") + " - " + zToDate.ToString("dd/MM") + " /" + zFromDate.ToString("yyyy");
            return View("~/Views/Desktop/Financial/Invoice/OUT.cshtml");
        }
        public ActionResult SearchInvoiceOUT_Date(string FromDate = "", string ToDate = "")
        {
            DateTime zFromDate = DateTime.Now;
            if (FromDate.Length > 0)
            {
                DateTime.TryParseExact(FromDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zFromDate);
            }

            DateTime zToDate = DateTime.Now;
            if (ToDate.Length > 0)
            {
                DateTime.TryParseExact(ToDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zToDate);
            }

            zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, zFromDate.Day, 0, 0, 0);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);
            ViewBag.DateView = zFromDate.ToString("dd/MM") + " - " + zToDate.ToString("dd/MM") + " /" + zFromDate.ToString("yyyy");
            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message1, zFromDate, zToDate, "", "OUT");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceOUT = ListInvoice;
            ViewBag.ListInvoiceIN = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message2, zFromDate, zToDate, "", "IN");

            return View("~/Views/Desktop/Financial/Invoice/OUT.cshtml");
        }
        /// <summary>
        /// Tìm theo button tới lui QUÝ
        /// </summary>
        /// <param name="btnAction"></param>
        /// <param name="DateView"></param>
        /// <returns></returns>
        public ActionResult SearchInvoiceOUT_Button(string btnAction = "", string DateView = "")
        {
            #region Datetime string to fromdate - todate
            int Month = DateTime.Now.Month;
            int Year = DateTime.Now.Year;
            if (DateView != string.Empty)
            {
                Month = DateView.Split('/')[0].ToInt();
                Year = DateView.Split('/')[1].ToInt();

                if (Year.ToString().Length < 4)
                {
                    Month = DateTime.Now.Month;
                    Year = DateTime.Now.Year;
                }
            }
            switch (btnAction)
            {
                case "btn_Prev":
                    Month = Month - 1;
                    break;
                case "btn_Next":
                    Month = Month + 1;
                    break;
            }
            if (Month <= 0)
            {
                Month = 12;
                Year = Year - 1;
            }
            if (Month >= 13)
            {
                Month = 1;
                Year = Year + 1;
            }
            DateTime zDateView = DateTime.Now;
            zDateView = new DateTime(Year, Month, 1, 23, 59, 59);
            DateTime zFromDate = new DateTime(zDateView.Year, zDateView.Month, 1, 0, 0, 0);
            DateTime zToDate = zFromDate.AddMonths(1).AddDays(-1);
            zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);
            #endregion
            ViewBag.DateView = Month + "/" + Year;
            var ListInvoice = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message1, zFromDate, zToDate, "", "OUT");
            TempData["ListExcel"] = ListInvoice;
            ViewBag.ListInvoiceOUT = ListInvoice;
            ViewBag.ListInvoiceIN = Invoice_Data.ListSearch(UserLog.PartnerNumber, out string Message2, zFromDate, zToDate, "", "IN");
            return View("~/Views/Desktop/Financial/Invoice/OUT.cshtml");
        }
        #endregion

        #region [Nhập, xóa, sửa hđ]
        [HttpPost]
        public JsonResult SaveInvoice()
        {
            ServerResult zResult = new ServerResult();
            try
            {
                string zInvoiceObj = Request.Form["InvoiceObj"];
                string zInvoiceKey = Request.Form["InvoiceKey"];

                Invoice_Model zModel = JsonConvert.DeserializeObject<Invoice_Model>(zInvoiceObj);
                if (zModel.PartnerKey == "NEW")
                {

Views/Desktop/Financial/Invoice/QuarterSummary.cshtml
@model Invoice_Quarter_Model
@{
    Layout = null;
}
<table class="table table-bordered table-sm">
    <tr>
        <th>#</th>
        <th>Nội dung</th>
        <th>Số tiền</th>
    </tr>
    <tr>
        <td>@("Q" + (Model.Previous == 0 ? 4: Model.Previous))</td>
        <td class="font-weight-semibold text-dark">A. Thuế giá trị gia tăng còn được khấu trừ chuyển qua</td>
        <td class="font-weight-semibold text-dark number">
            @Model.AmountPrevious
        </td>

    </tr>
    @{
        <tr>
            <td rowspan="11">@("Q" + Model.Current)</td>
            <td class="font-weight-semibold text-dark">B. Doanh số bán ra chịu thuế</td>
            <td class="font-weight-semibold text-dark number">
                @Model.IncomeWithV
            </td>

        </tr>
        <tr>

            <td class="font-weight-semibold text-dark">C. Doanh số bán ra không chịu thuế</td>
            <td class="font-weight-semibold text-dark number">
                @Model.IncomeNoV
            </td>

        </tr>
        <tr>

            <td class="font-weight-semibold text-dark">D. Tổng doanh số</td>
            <td class="font-weight-semibold text-dark number">
                @Model.InComeTotal
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-dark">E. Thuế GTGT đầu vào Q4</td>
            <td class="font-weight-semibold text-dark number">
                @Model.AmountVatInTotal
            </td>

        </tr>
        <tr>

            <td class="font-weight-semibold text-danger"> - Số VAT đầu vào trực tiếp</td>
            <td class="font-weight-semibold text-danger number">
                @Model.AmountVatInDirect
            </td>

        </tr>
        <tr>

            <td class="font-weight-semibold text-dark"> - Số VAT đầu vào dùng chung</td>
            <td class="font-weight-semibold text-dark number">
                @Model.AmountVatInShare
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-danger">F. Số VAT được khấu trừ của hóa đơn dùng chung</td>
            <td class="font-weight-semibold text-danger number">
                @Model.AmountVatInShareToMinus
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-dark">G. Tổng số VAT được trừ trong quý</td>
            <td class="font-weight-semibold text-dark number">
                @Model.AmountVatAllowMinus
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-dark">H. Thuế GTGT đầu ra Q4</td>
            <td class="font-weight-semibold text-dark number">
                @Model.AmountVatOutTotal
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-danger">K. Số tiền nộp thuế của quý hiện tại</td>
            <td class="font-weight-semibold text-danger number">
                @Model.AmountPayCurrent
            </td>

        </tr>
        <tr>
            <td class="font-weight-semibold text-dark">J. Số tiền nộp thuế khi cộng quý trước</td>
            <td class="font-weight-semibold text-dark number">
                @Model.AmountPayInclude
            </td>

        </tr>
    }
</table>

Views/Desktop/Financial/Invoice/Year.cshtml
@{
    ViewBag.Title = "Year";
    Layout = "~/Views/Shared/_Layout_Desktop.cshtml";
    List<Invoice_Model> _ListInvoiceIN = new List<Invoice_Model>();
    if (ViewBag.ListInvoiceIN != null)
    {
        _ListInvoiceIN = ViewBag.ListInvoiceIN as List<Invoice_Model>;
    }
    List<Invoice_Model> _ListInvoiceOUT = new List<Invoice_Model>();
    if (ViewBag.ListInvoiceOUT != null)
    {
        _ListInvoiceOUT = ViewBag.ListInvoiceOUT as List<Invoice_Model>;
    }
    string _DateView = ViewBag.DateView.ToString();
}

<header class="page-header">
    <h2>Thuế GTGT (Năm)</h2>
    <div class="right-wrapper number">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>

                </a>
            </li>
            <li>
            </li>
        </ol>
    </div>
</header>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form action="@Url.Action("InvoiceBalanceYear","Financial")" id="YearForm">
                    <table class="table mb-0 Custom">
                        <tr>
                            <td class="text-left">
                                <button type="submit" class="btn btn-info btn-block" name="btnAction" value="btn_Prev">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                            </td>
                            <td class="text-center" onclick="OpenDate()">
                                <h4 class="font-weight-semibold text-primary">
                                    Năm @_DateView
                                    <i class="fas fa-caret-down"></i>
                                </h4>
                            </td>
                            <td class="text-right">
                                <button type="submit" class="btn btn-info btn-block" name="btnAction" value="btn_Next">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </td>
                        </tr>
                    </table>
                    <input type="hidden" name="DateView" value="@_DateView" />
                </form>
            </div>
        </div>
        <div class="card-body">
            @Html.Raw(ViewBag.HtmlData)
        </div>
    </div>
</div>

<!---->
<div id="modalDate" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
    <div class="card border border-primary">
        <div class="card-header">
            <h2 class="card-title">Tùy chọn thời gian</h2>
        </div>
        <div class="card-body border-primary">
            <div class="form-group">
                <div class="radio-custom radio-warning">
                    <input type="radio" id="radioQuarter" name="radioView" value="Quarter" checked>
                    <label for="radioQuarter">Xem theo quý</label>
                </div>
                <div class="radio-custom radio-warning">
                    <input type="radio" id="radioYear" name="radioView" value="Year">
                    <label for="radioYear">Xem theo năm</label>
                </div>
            </div>
            <div class="card-footer border-primary text-center">
                <button type="button" class="btn btn-outline-primary modal-dismiss">
                    <i class="far fa-times-circle"></i>
                    Đóng
                </button>
                <button type="button" class="btn btn-outline-primary modal-confirm" onclick="SetView()">
                    <i class="fas fa-search"></i>
                    OK
                </button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        var URL_Quarter = '@Url.Action("InvoiceBalanceQuarter", "Financial")';
        var URL_Year = '@Url.Action("InvoiceBalanceYear", "Financial")';
    </script>
    <script>
        $(document).ready(function () {

        });
        function OpenDate() {
            Utils.OpenMagnific("#modalDate");
        }
        function SetView() {
            var val = $("#modalDate input[type='radio']:checked").val();
            if (val == "Quarter") {
                window.location.href = URL_Quarter;
            }
            if (val == "Year") {
                window.location.href = URL_Year;
            }
        }
    </script>
}