Controllers/Core/ConfigController.cs
using Newtonsoft.Json;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace TNStores.Controllers
{
    public class ConfigController : BaseController
    {
        private static string VIEWTYPE = UserLog.VIEWTYPE;
        //#region DÙNG CHUNG CHO DESKTOP VÀ MOBILE
        //public ActionResult A_InfoBill()
        //{
        //    string PartnerNumber = UserLog.PartnerNumber;
        //    Partner_Info zInfo = new Partner_Info(PartnerNumber);           
        //    ViewBag.Data = zInfo.Partner.BillConfig;

        //    string zPageView = "~/Views/" + VIEWTYPE + "/Config/BillInfo.cshtml";
        //    return View(zPageView, );
        //}

        //public ActionResult A_InfoBillUpdate(HttpPostedFileBase[] files, string Title = "", string Description = "", string End = "")
        //{
        //    User_Model zUser = Session["User_Model"] as User_Model;
        //    string PartnerNumber = zUser.PartnerNumber;
        //    Partner_Info zInfo = new Partner_Info(PartnerNumber);
        //    string Data = zInfo.Partner.BillConfig;
        //    string base64String = "";
        //    if (Title != string.Empty ||
        //        Description != string.Empty ||
        //        End != string.Empty)
        //    {

        //        if (files.Length > 0)
        //        {
        //            if (files[0] != null)
        //            {
        //                Stream fs = files[0].InputStream;
        //                BinaryReader br = new BinaryReader(fs);
        //                Byte[] bytes = br.ReadBytes((Int32)fs.Length);
        //                base64String = Convert.ToBase64String(bytes, 0, bytes.Length);
        //                base64String = "data:image/png;base64," + base64String;
        //            }
        //        }
        //    }

        //    if (base64String == string.Empty &&
        //        zInfo.Partner.Logo_Large.Length > 0)
        //    {
        //        base64String = zInfo.Partner.Logo_Large;
        //    }

        //    Data = Title.Trim() + "|" + Description.Trim() + "|" + End.Trim() + "|" + base64String;
        //    zInfo.Partner.PartnerNumber = PartnerNumber;
        //    zInfo.UpdateBill(Data);

        //    if (zInfo.Code == "200" ||
        //        zInfo.Code == "201")
        //    {
        //        ViewBag.Message = "Cập nhật thành công !.";
        //    }
        //    else
        //    {
        //        ViewBag.Message = "Lỗi " + zInfo.Message;
        //    }

        //    ViewBag.Data = Data;
        //    return RedirectToAction("A_InfoBill");
        //}

        //public ActionResult A_InfoStore()
        //{
        //    string PartnerNumber = UserLog.PartnerNumber;
        //    Partner_Info zInfo = new Partner_Info(PartnerNumber);

        //    return View("~/Views/Desktop/Config/StoreInfo.cshtml", zInfo.Partner);
        //}
        //#endregion







        // GET: Config   

        #region[-                  -]
        [HttpGet]
        public JsonResult CheckIDProduct(string ProductID)
        {
            ServerResult zResult = new ServerResult();
            Product_Info zInfo = new Product_Info(ProductID, true);
            if (zInfo.Code == "200")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Data = TN_Utils.QRWrite(ProductID, out string Message);
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public JsonResult GetIDProduct()
        {
            string ID = Helper.AutoID_Product(UserLog.PartnerNumber, "SKU");
            return Json(ID, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CategoryLevel1()
        {
            ViewBag.ListProductCategory = Product_Category_Data.List(UserLog.PartnerNumber, out string Message, 1, false);
            return View("~/Views/Desktop/Config/CategoryLevel1.cshtml");
        }
        public ActionResult CategoryLevel2()
        {
            ViewBag.ListProductCategory = Product_Category_Data.List(UserLog.PartnerNumber, out string Message, 2, false);
            ViewBag.ListLevel1 = Product_Category_Data.List(UserLog.PartnerNumber, out string Message1, 1, false);
            return View("~/Views/Desktop/Config/CategoryLevel2.cshtml");
        }
        [HttpPost]
        public JsonResult SaveProductCategory(int CategoryKey, string CategoryNameVN, string CategoryNameEN, string CategoryNameCN, string Description, int Parent, int Rank, int Level)
        {
            ServerResult zResult = new ServerResult();
            Product_Category_Info zInfo = new Product_Category_Info(CategoryKey);

            zInfo.Product_Category.PartnerNumber = UserLog.PartnerNumber;
            zInfo.Product_Category.CategoryKey = CategoryKey;
            zInfo.Product_Category.CategoryNameVN = CategoryNameVN.Trim();
            zInfo.Product_Category.CategoryNameEN = CategoryNameEN.Trim();
            zInfo.Product_Category.CategoryNameCN = CategoryNameCN.Trim();
            zInfo.Product_Category.Description = Description.Trim();
            zInfo.Product_Category.Parent = Parent.ToInt();
            zInfo.Product_Category.Rank = Rank.ToInt();
            zInfo.Product_Category.Level = Level.ToInt();

            if (zInfo.Product_Category.CategoryKey == 0)
            {
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public JsonResult DetailProductCategory(int CategoryKey)
        {
            ServerResult zResult = new ServerResult();
            Product_Category_Info zInfo = new Product_Category_Info(CategoryKey);
            Product_Category_Model zModel = zInfo.Product_Category;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public JsonResult DeleteProductCategory(int CategoryKey)
        {
            ServerResult zResult = new ServerResult();
            Product_Category_Info zInfo = new Product_Category_Info();
            zInfo.Product_Category.CategoryKey = CategoryKey;
            zInfo.Delete();
            //Product_Category_Model zModel = zInfo.Product_Category;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ListProduct()
        {
            ViewBag.ListProduct = Product_Data.List(UserLog.PartnerNumber, out string Message);
            ViewBag.ListProductCategory = Product_Data.ListCategory(UserLog.PartnerNumber, out string Message1);
            ViewBag.ListProductUnit = Product_Unit_Data.List(UserLog.PartnerNumber, out string Message2);
            return View("~/Views/Desktop/Config/Product.cshtml");
        }
        [HttpPost]
        public JsonResult SaveProduct()
        {
            ServerResult zResult = new ServerResult();
            try
            {
                string zProductObj = Request.Form["ProductObj"];
                string zProductKey = Request.Form["ProductKey"];

                #region [Apply data to model]
                Product_Model zModel = JsonConvert.DeserializeObject<Product_Model>(zProductObj);
                zModel.PartnerNumber = UserLog.PartnerNumber;
                zModel.CreatedBy = UserLog.UserKey;
                zModel.CreatedName = UserLog.EmployeeName;
                zModel.ModifiedBy = UserLog.ModifiedBy;
                zModel.ModifiedName = UserLog.EmployeeName;

                if (zModel.PhotoPath.Length > 0)
                {
                    string Message = "";
                    Helper.DeleteSingleFile(zModel.PhotoPath, out Message);
                }

                if (Request.Files.Count > 0)
                {
                    string zFilePath = Helper.UploadPath + "/Product/";
                    HttpPostedFileBase files = Request.Files[0];
                    bool zUploadResult = Helper.UploadSingleFile(files, zFilePath, out zFilePath);
                    if (zUploadResult)
                    {
                        zModel.PhotoPath = zFilePath;
                    }
                }
                #endregion

                #region [Save data to db]
                Product_Info zInfo = new Product_Info(zProductKey);
                zInfo.Product = zModel;

                if (zInfo.Product.ProductKey == "")
                {
                    zInfo.Create_ServerKey();
                }
                else
                {
                    zInfo.Update();

Views/Desktop/Config/BillInfo.cshtml
@{
    ViewBag.Title = "BillInfo";
    Layout = "~/Views/Shared/_Layout_Desktop.cshtml";

    string[] Data = new string[4] { "", "", "", "" };
    if (ViewBag.Data != null)
    {
        string temp = ViewBag.Data as string;
        if (temp.Contains("|"))
        {
            Data = temp.Split('|');
        }
    }
}

<header class="page-header">
    <h2>Thông tin mẫu in bill</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>

<form class="card" action="@Url.Action("UpdateBill","Config")" method="post" enctype="multipart/form-data">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group text-center">
                    @if (Data[3] == string.Empty)
                    {
                        <img id="imgpreview" src="@Url.Content("~/assets/themes/img/unnamed.png")" alt="your image" style="max-width: -webkit-fill-available; max-height:200px;" />
                    }
                    else
                    {
                        <img id="imgpreview" src="@Url.Content(Data[3])" alt="your image" style="max-width: -webkit-fill-available; max-height:200px;" />
                    }
                    <br />
                    <input type="file" id="fileListPhoto" multiple name="files">
                </div>
                <div class="form-group row">
                    <label class="col-lg-5 col-xl-3 control-label text-lg-right">
                        Tiêu đề
                    </label>
                    <div class="col-lg-7 col-xl-9">
                        <input type="text" class="form-control" name="Title" value="@Data[0]" required="" id="txt_Title">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5 col-xl-3 control-label text-lg-right">
                        Ghi chú
                    </label>
                    <div class="col-lg-7 col-xl-9">
                        <textarea class="form-control" name="Description" required="" id="txt_Description">@Data[1]</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5 col-xl-3 control-label text-lg-right">
                        Cuối trang
                    </label>
                    <div class="col-lg-7 col-xl-9">
                        <input type="text" class="form-control" name="End" value="@Data[2]" required="" id="txt_End">
                    </div>
                </div>
            </div>
            <div class="col-md-4 border-left">

            </div>
        </div>
    </div>
    <div class="card-footer">
        <button id="btn_Save" type="submit" class="btn btn-outline-primary">
            <i class="far fa-save"></i>
            Cập nhật
        </button>
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>@ViewBag.Message</strong>.
            </div>
        }
    </div>
</form>
@section scripts{
    <script>
        $("#imgpreview").click(function () {
            $("#fileListPhoto").trigger('click');
        });
        $("#fileListPhoto").change(function () {
            Utils.PreviewImg(this, "#imgpreview");
            var str = $("#imgpreview").attr("src");
            $("#txt_Base64String").val(str);
        });
    </script>
}

Views/Desktop/Config/CategoryLevel1.cshtml
@{
    ViewBag.Title = "CategoryLevel1";
    Layout = "~/Views/Shared/_Layout_Desktop.cshtml";

    List<Product_Category_Model> _ListCategory = new List<Product_Category_Model>();
    if (ViewBag.ListProductCategory != null)
    {
        _ListCategory = ViewBag.ListProductCategory as List<Product_Category_Model>;
    }
}

<header class="page-header">
    <h2>Danh mục sản phẩm cấp 1</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="card border ">
            <div class="card-header ">

            </div>
            <div class="card-body ">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            @*<th>Mã số</th>*@
                            <th>Tên danh mục</th>
                            <th>Diễn giải</th>
                            <th>Thứ tự</th>
                            <th class="text-right">
                                <button class="modal-with-zoom-anim btn btn-info" type="button" onclick="Detail(0)">
                                    <i class="fa fa-plus"></i>
                                    Thêm mới
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tblBody">

                        @{
                            if (_ListCategory.Count > 0)
                            {
                                for (int i = 0; i < _ListCategory.Count; i++)
                                {
                                    Product_Category_Model zModel = _ListCategory[i];
                                    string Key = zModel.CategoryKey.ToString();
                                    string No = (i + 1).ToString();
                                    string CategoryName = zModel.CategoryNameVN;
                                    string Description = zModel.Description;
                                    int Rank = zModel.Rank;

                                    <tr>
                                        <th>@No</th>
                                        @*<td>@Key</td>*@
                                        <td>@CategoryName</td>
                                        <td>@Description</td>
                                        <td>@Rank</td>
                                        <td class="text-right">
                                            <button type="button" class="btn btn-outline-primary btn-sm modal-with-zoom-anim" onclick="Detail(@Key)">
                                                <i class="far fa-edit"></i>
                                            </button>
                                            <button type="button" class="btn btn-outline-danger btn-sm" onclick="Delete(@Key)">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7">
                                        <div class="alert alert-primary">
                                            <strong>Bạn chưa cập nhật, hoặc không tìm thấy dữ liệu phù hợp !</strong>.
                                        </div>
                                    </td>
                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer ">
            </div>
        </div>

    </div>
</div>

<div id="modalEdit" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">

    <div class="card border ">
        <div class="card-header">
            <h2 class="card-title">Thông tin danh mục sản phẩm cấp 1</h2>
        </div>
        <div class="card-body ">
            <div class="form-group row">
                <label for="positionid" class="col-lg-5 col-xl-3 control-label text-lg-right">Tên danh mục(VN)</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_CategoryNameVN" value="" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="positionid" class="col-lg-5 col-xl-3 control-label text-lg-right">Tên danh mục(EN)</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_CategoryNameEN" value="" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="positionid" class="col-lg-5 col-xl-3 control-label text-lg-right">Tên danh mục(CN)</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_CategoryNameCN" value="" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-lg-right">Diễn giải</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control " id="txt_Description" value="" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="positionid" class="col-lg-5 col-xl-3 control-label text-lg-right">Thứ tự hiển thị</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="number" class="form-control number" id="txt_Rank" value="0" placeholder="">
                </div>
            </div>
            <div class="card-footer  text-center">
                <button id="btn_Cancel" type="button" class="btn btn-outline-secondary modal-dismiss">
                    <i class="far fa-times-circle"></i>
                    Đóng
                </button>
                <button id="btn_Save" type="button" class="btn btn-outline-primary modal-confirm" onclick="Save()">
                    <i class="far fa-save"></i>
                    Cập nhật
                </button>
            </div>
        </div>
    </div>
    <input id="txt_CategoryKey" type="hidden" name="FeaKey" value="0" />
</div>

<script>
        var URL_Detail = "@Url.Action("DetailProductCategory", "Config")";
        var URL_Delete = "@Url.Action("DeleteProductCategory", "Config")";
        var URL_Save = "@Url.Action("SaveProductCategory", "Config")";

        $(document).ready(function () {

        });

        function Save() {
            var CategoryKey = $("#txt_CategoryKey").val();
            var CategoryNameVN = $("#txt_CategoryNameVN").val();
            var CategoryNameEN = $("#txt_CategoryNameEN").val();
            var CategoryNameCN = $("#txt_CategoryNameCN").val();
            var Description = $("#txt_Description").val();
            var Rank = $("#txt_Rank").val();
            var Parent = 0;
            var Level = 1;
            $.ajax({
                url: URL_Save,
                type: "POST",
                data: {
                    "CategoryKey": CategoryKey,
                    "CategoryNameVN": CategoryNameVN,
                    "CategoryNameEN": CategoryNameEN,
                    "CategoryNameCN": CategoryNameCN,
                    "Description": Description,
                    "Rank": Rank,
                    "Parent": Parent,
                    "Level": Level,
                },
                beforeSend: function () {
                    Utils.LoadIn();
                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                    }
                },
                error: function (err) {
                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                },
                complete: function () {
                    Utils.LoadOut();
                }
            });
        }
        function Detail(CategoryKey) {
            Utils.OpenMagnific("#modalEdit");
            if (CategoryKey > 0) {
                $.ajax({
                    url: URL_Detail,
                    type: "GET",
                    data: {
                        "CategoryKey": CategoryKey
                    },
                    beforeSend: function () {
                        Utils.LoadIn();
                    },
                    success: function (r) {
                        if (r.Success) {
                            var obj = JSON.parse(r.Data);
                            $("#txt_CategoryKey").val(obj.CategoryKey);
                            $("#txt_CategoryNameVN").val(obj.CategoryNameVN);
                            $("#txt_CategoryNameEN").val(obj.CategoryNameEN);
                            $("#txt_CategoryNameCN").val(obj.CategoryNameCN);
                            $("#txt_Description").val(obj.Description);
                            $("#txt_Rank").val(obj.Rank);
                        }
                        else {
                            Utils.OpenNotify(r.Message, "Thông báo", "error");
                        }
                    },
                    error: function (err) {
                        Utils.OpenNotify(err.responseText, "Thông báo", "error");
                    },
                    complete: function () {
                        Utils.LoadOut();
                    }
                });
            }
            else {
                Utils.ClearUI("#modalEdit");
                $("#txt_CategoryKey").val(0);
                $("#txt_Rank").val(0);
            }
        }
        function Delete(CategoryKey) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: "POST",
                                data: {
                                    "CategoryKey": CategoryKey
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.Success) {
                                        location.reload();
                                    }
                                    else {
                                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }

</script>

Views/Desktop/Config/CategoryPayment.cshtml
@{
    ViewBag.Title = "CategoryPayment";
    Layout = "~/Views/Shared/_Layout_Desktop.cshtml";
    List<CashPayment_Category_Model> _ListData = new List<CashPayment_Category_Model>();
    if (ViewBag.List != null)
    {
        _ListData = ViewBag.List as List<CashPayment_Category_Model>;
    }
}

<header class="page-header">
    <h2>Danh mục chi phí</h2>
    <div class="right-wrapper text-right" style="margin-right:10px">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
        </ol>
    </div>

</header>
<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header ">
                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-primary float-right" type="button" id="btnAdd" onclick="Save(0)">
                            <i class="fa fa-plus"></i> Thêm
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body ">
                @foreach (CashPayment_Category_Model zItem in _ListData)
                {
                    <div class="form-group row" key="@zItem.CategoryKey">
                        <div class="col-12">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="" key="@zItem.CategoryKey" value="@zItem.CategoryNameVN" />
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-outline-primary" onclick="Save(@zItem.CategoryKey)">
                                        <i class="far fa-save"></i> Lưu
                                    </button>
                                    <button type="button" class="btn btn-outline-danger" onclick="Delete(@zItem.CategoryKey)">
                                        <i class="fas fa-trash"></i> Xóa
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="card-footer ">
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        var URL_Save = '@Url.Action("SaveCategory", "Config")';
        var URL_Delete = '@Url.Action("DeleteCategory", "Config")';
        var height = $(window).height() - 350;

        $(document).ready(function () {

        });

        function Delete(Key) {
            if (confirm('Bạn có chắc xóa thông tin !.')) {
                $.ajax({
                    url: URL_Delete,
                    type: 'POST',
                    data: {
                        "CategoryKey": Key,
                        "Type": "Payment"
                    },
                    beforeSend: function () {

                    },
                    success: function (r) {
                        if (r.Success) {
                            location.reload();
                        }
                        else {
                            alert(r.Message);
                        }
                    },
                    error: function (err) {
                        console.log(err.responseText);
                    },
                    complete: function () {

                    }
                });
            }
        }
        function Save(Key) {
            var name = 'Nội dung mới';
            if (Key != 0)
            {
                name = $("input[key=" + Key + "]").val();
            }
            $.ajax({
                url: URL_Save,
                type: 'POST',
                data: {
                    "CategoryKey": Key,
                    "CategoryName": name,
                    "Type": "Payment"
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        alert(r.Message);
                    }
                },
                error: function (err) {
                    console.log(err.responseText);
                },
                complete: function () {

                }
            });
        }
    </script>
}