Controllers/MobileController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace TNStores.Controllers
{
    public class MobileController : BaseController
    {
        public ActionResult mDashboard(string btnAction = "", string FromDate = "", string ToDate = "",
        string Option = "DONHANG,DOANHSO,THUCTHU,PHAITHU,CHIPHI,TON",
        string Color = "#383f4882,#0088cc82,#e361598f,#2baab194,#8000807a,#ffa50080")
        {
            string Message = "";
            DateTime zFromDate;
            DateTime zToDate;
            if (FromDate == string.Empty &&
                ToDate == string.Empty)
            {
                zFromDate = FirstDayOfWeek(DateTime.Now);
                zToDate = LastDayOfWeek(DateTime.Now);

                zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, zFromDate.Day, 0, 0, 0);
                zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);
            }
            else
            {
                DateTime.TryParseExact(FromDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zFromDate);
                DateTime.TryParseExact(ToDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out zToDate);
                zFromDate = new DateTime(zFromDate.Year, zFromDate.Month, zFromDate.Day, 0, 0, 0);
                zToDate = new DateTime(zToDate.Year, zToDate.Month, zToDate.Day, 23, 59, 59);

                switch (btnAction)
                {
                    case "btn_Prev":
                        zFromDate = zFromDate.AddDays(-6);
                        zToDate = zToDate.AddDays(-6);
                        break;
                    case "btn_Next":
                        zFromDate = zFromDate.AddDays(+6);
                        zToDate = zToDate.AddDays(+6);
                        break;
                }
            }

            ViewBag.FromDate = zFromDate.ToString("dd/MM/yyyy");
            ViewBag.ToDate = zToDate.ToString("dd/MM/yyyy");

            ViewBag.Option = Option;
            ViewBag.SaleAmount = Helper.rpt_SaleAmount(UserLog.PartnerNumber, zFromDate, zToDate, out Message);
            ViewBag.OrderTotal = Helper.rpt_OrderTotal(UserLog.PartnerNumber, zFromDate, zToDate, out Message);
            ViewBag.InCome = Helper.rpt_InCome(UserLog.PartnerNumber, zFromDate, zToDate, out Message);
            ViewBag.OrderDebt = Helper.rpt_OrderDebt(UserLog.PartnerNumber, zFromDate, zToDate, out Message);
            ViewBag.Payment = Helper.rpt_Payment(UserLog.PartnerNumber, zFromDate, zToDate, out Message);

            DataTable zTable = Helper.DB_ChartAIO(UserLog.PartnerNumber, Option, Color, zFromDate, zToDate, out Message);
            if (zTable.Rows.Count > 0)
            {
                ViewBag.Label = ChartJS_XLabelName(zTable);
                ViewBag.Dataset = ChartJS_Dataset(zTable);
            }

            //ViewBag.ListOrder = Order_Data.List(UserLog.PartnerNumber, out Message, zFromDate, zToDate);
            //ViewBag.ListPayment = Payment_Data.ListSearch(UserLog.PartnerNumber, out Message, zFromDate, zToDate, "");

            return View("~/Views/Mobile/Sale/Week.cshtml");
        }

        //trang chuyển tiếp đầu tiên trên mobile
        public ActionResult Index()
        {
            return View();
        }

        #region Setting - config
        public ActionResult Setting()
        {
            return View("~/Views/Mobile/Config/Index.cshtml");
        }

        #region [Product Category]
        [HttpPost]
        public JsonResult SaveCategoryProduct(int CategoryKey = 0, string CategoryName = "", int Level = 1, int Parent = 0, int Rank = 0)
        {
            ServerResult zResult = new ServerResult();
            Product_Category_Info zInfo = new Product_Category_Info(CategoryKey);

            zInfo.Product_Category.PartnerNumber = UserLog.PartnerNumber;
            zInfo.Product_Category.CategoryKey = CategoryKey;
            zInfo.Product_Category.CategoryNameVN = CategoryName.Trim();
            zInfo.Product_Category.Parent = Parent.ToInt();
            zInfo.Product_Category.Rank = Rank.ToInt();
            zInfo.Product_Category.Level = Level.ToInt();

            if (zInfo.Product_Category.CategoryKey == 0)
            {
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DeleteProductCategory(int CategoryKey)
        {
            ServerResult zResult = new ServerResult();
            Product_Category_Info zInfo = new Product_Category_Info();
            zInfo.Product_Category.CategoryKey = CategoryKey;
            zInfo.Delete();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CategoryProduct()
        {
            ViewBag.ListData = Product_Category_Data.List(UserLog.PartnerNumber, out string Message, 1, false);
            return View("~/Views/Mobile/Config/CategoryProduct.cshtml");
        }
        #endregion

        #region Product
        [HttpGet]
        public JsonResult CheckIDProduct(string ProductID)
        {
            ServerResult zResult = new ServerResult();
            Product_Info zInfo = new Product_Info(ProductID, true);
            if (zInfo.Code == "200")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Data = TN_Utils.QRWrite(ProductID, out string Message);
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public JsonResult GetIDProduct()
        {
            string ID = Helper.AutoID_Product(UserLog.PartnerNumber, "SKU");
            return Json(ID, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListProduct()
        {
            ViewBag.ListProduct = Product_Data.List(UserLog.PartnerNumber, out string Message);
            return View("~/Views/Mobile/Config/Product.cshtml");
        }

        public ActionResult ProductEdit(string ProductKey = "")
        {
            ViewBag.ListUnit = Product_Unit_Data.List(UserLog.PartnerNumber, out string Message);
            ViewBag.ListCategory = Product_Data.ListCategory(UserLog.PartnerNumber, out Message);
            Product_Info zInfo = new Product_Info(ProductKey);
            if (ProductKey.Length <= 0)
            {
                zInfo.Product.ProductID = Helper.AutoID_Product(UserLog.PartnerNumber, "SKU");
            }

            return View("~/Views/Mobile/Config/ProductEdit.cshtml", zInfo.Product);
        }

        [HttpPost]
        public JsonResult SaveProduct()
        {
            ServerResult zResult = new ServerResult();
            try
            {
                string zProductObj = Request.Form["ProductObj"];
                string zProductKey = Request.Form["ProductKey"];

                #region [Apply data to model]
                Product_Model zModel = JsonConvert.DeserializeObject<Product_Model>(zProductObj);
                zModel.PartnerNumber = UserLog.PartnerNumber;
                zModel.CreatedBy = UserLog.UserKey;
                zModel.CreatedName = UserLog.EmployeeName;
                zModel.ModifiedBy = UserLog.ModifiedBy;
                zModel.ModifiedName = UserLog.EmployeeName;

                if (zModel.PhotoPath.Length > 0)
                {
                    string Message = "";
                    Helper.DeleteSingleFile(zModel.PhotoPath, out Message);
                }

                if (Request.Files.Count > 0)
                {
                    string zFilePath = Helper.UploadPath + "/Product/";
                    HttpPostedFileBase files = Request.Files[0];
                    bool zUploadResult = Helper.UploadSingleFile(files, zFilePath, out zFilePath);
                    if (zUploadResult)
                    {
                        zModel.PhotoPath = zFilePath;
                    }
                }
                #endregion

                #region [Save data to db]
                Product_Info zInfo = new Product_Info(zProductKey);
                zInfo.Product = zModel;

                if (zInfo.Product.ProductKey == "")
                {
                    zInfo.Create_ServerKey();
                }
                else
                {
                    zInfo.Update();
                }
                #endregion

                if (zInfo.Code == "200" ||
                    zInfo.Code == "201")
                {
                    zResult.Success = true;
                    return Json(zResult, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    zResult.Success = false;
                    zResult.Message = zInfo.Message;
                    return Json(zResult, JsonRequestBehavior.AllowGet);
                }

Views/Mobile/Config/BillInfo.cshtml
@{
    ViewBag.Title = "BillInfo";
    Layout = "~/Views/Shared/_Layout_mHome.cshtml";
    string[] Data = new string[4] { "", "", "", "" };
    if (ViewBag.Data != null)
    {
        string temp = ViewBag.Data as string;
        if (temp.Contains("|"))
        {
            Data = temp.Split('|');
        }
    }
}
<div class="row m-0 border border-top bg-white pageHead">
    <div class="col-md-12 p-0">
        <table class="table table-borderd">
            <tr>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="@Url.RouteUrl("mCaiDat")">
                        <i class="fas fa-2x fa-angle-left"></i>
                    </a>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <h4>Mẫu in hóa đơn</h4>
                </td>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="#" id="btn_Save" style="display:inline-block;width: 100%;">
                        <i class="fas fa-2x fa-check"></i>
                    </a>
                </td>
            </tr>
        </table>

    </div>
</div>
<form class="card" action="@Url.Action("BillConfig","Mobile")" method="post" enctype="multipart/form-data" id="frmSubmit">
    <div class="card-body" style="padding-top:72px !important;">
        <div class="form-group mt-2 text-center">
            @if (Data[3] == string.Empty)
            {
                <img id="imgpreview" src="@Url.Content("~/assets/themes/img/unnamed.png")" alt="your image" style="height:200px;" />
            }
            else
            {
                <img id="imgpreview" src="@Url.Content(Data[3])" alt="your image" style="height:200px;" />
            }
            <br />
            <input type="file" id="fileListPhoto" multiple name="files" accept="image/*;capture=camera" style="display:none;">
           <span class="text-danger">Lưu ý: Phần mềm sẽ tự động lấy logo cửa hàng nếu logo hóa đơn để trống</span>
        </div>
        <div class="form-label-group">
            <label class="" for="txt_Title">
                Tiêu đề hóa đơn
            </label>
            <input type="text" class="form-control" name="Title" value="@Data[0]" id="txt_Title">
        </div>

        <div class="form-label-group">
            <textarea class="form-control" name="Description" id="txt_Description" placeholder="Ghi chú hóa đơn">@Data[1]</textarea>
        </div>
        <div class="form-label-group">
            <label class="" for="txt_End">
                Cuối hóa đơn
            </label>
            <input type="text" class="form-control" name="End" value="@Data[2]" id="txt_End">
        </div>
    </div>
    <div class="card-footer text-center">
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>@ViewBag.Message</strong>.
            </div>
        }
    </div>
</form>

@section scripts{
    <script>
        $(".header").remove();
        $("#btn_Save").click(function () {
            $("#frmSubmit").submit();
        });
        $("#imgpreview").click(function () {
            $("#fileListPhoto").trigger('click');
        });
        $("#fileListPhoto").change(function () {
            Utils.PreviewImg(this, "#imgpreview");
            var str = $("#imgpreview").attr("src");
            $("#txt_Base64String").val(str);
        });
    </script>
}

Views/Mobile/Config/CategoryPayment.cshtml
@{
    ViewBag.Title = "CategoryPayment";
    Layout = "~/Views/Shared/_Layout_mHome.cshtml";
    List<CashPayment_Category_Model> _ListData = new List<CashPayment_Category_Model>();
    if (ViewBag.List != null)
    {
        _ListData = ViewBag.List as List<CashPayment_Category_Model>;
    }
}
<div class="row m-0 border border-top bg-white pageHead">
    <div class="col-md-12 p-0">
        <table class="table table-borderd mb-0">
            <tr>
                <td class="text-center" style="vertical-align: middle; width:15%" onclick="Utils.BackWithRefresh()">
                    <a href="@Url.RouteUrl("mCaiDat")">
                        <i class="fas fa-2x fa-angle-left"></i>
                    </a>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <h4>Danh mục chi phí</h4>
                </td>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="#" onclick="Save(0)">
                        <i class="fas fa-2x fa-plus"></i>
                    </a>
                </td>
            </tr>
        </table>

    </div>
</div>

<div class="bg-white" style="padding-top:72px !important;">
    @foreach (CashPayment_Category_Model zItem in _ListData)
    {
        <div class="form-group row mb-0" key="@zItem.CategoryKey">
            <div class="col-12">
                <div class="input-group">
                    <input type="text" class="form-control rounded-0" placeholder="" key="@zItem.CategoryKey" value="@zItem.CategoryNameVN" />
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-primary rounded-0" onclick="Save(@zItem.CategoryKey)">
                            <i class="far fa-save"></i>
                        </button>
                        <button type="button" class="btn btn-outline-danger rounded-0" onclick="Delete(@zItem.CategoryKey)">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script>
        var URL_Save = "@Url.Action("SaveCategory", "Mobile")";
        var URL_Delete = "@Url.Action("DeleteCategory", "Mobile")";
        var height = $(window).height() - 350;

        $(document).ready(function () {
            $(".header").remove();
        });

        function Delete(Key) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: 'POST',
                                data: {
                                    "CategoryKey": Key,
                                    "Type": "Payment"
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.Success) {                                       
                                        $("div[key=\"" + Key + "\"]")
                                            .css({ 'background': 'red', 'color': 'white' })
                                            .fadeOut(500, function () { $(this).remove(); });
                                        return false;
                                    }
                                    else {
                                        alert(r.Message);
                                    }
                                },
                                error: function (err) {
                                    console.log(err.responseText);
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }
        function Save(Key) {
            var name = 'Nội dung mới';
            if (Key != 0)
            {
                name = $("input[key=" + Key + "]").val();
            }
            $.ajax({
                url: URL_Save,
                type: 'POST',
                data: {
                    "CategoryKey": Key,
                    "CategoryName": name,
                    "Type": "Payment"
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        alert(r.Message);
                    }
                },
                error: function (err) {
                    console.log(err.responseText);
                },
                complete: function () {

                }
            });
        }
    </script>
}

Views/Mobile/Config/CategoryProduct.cshtml
@{
    ViewBag.Title = "CategoryProduct";
    Layout = "~/Views/Shared/_Layout_mHome.cshtml";
    var _ListData = new List<Product_Category_Model>();
    if (ViewBag.ListData != null)
    {
        _ListData = ViewBag.ListData as List<Product_Category_Model>;
    }
}
<div class="row m-0 border border-top bg-white pageHead">
    <div class="col-md-12 p-0">
        <table class="table table-borderd mb-0">
            <tr>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="@Url.RouteUrl("mCaiDat")">
                        <i class="fas fa-2x fa-angle-left"></i>
                    </a>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <h4>Danh mục sản phẩm</h4>
                </td>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="#" onclick="Save(0)">
                        <i class="fas fa-2x fa-plus"></i>
                    </a>
                </td>
            </tr>
        </table>

    </div>
</div>
<div class="bg-white" style="padding-top:72px !important;">
    @foreach (Product_Category_Model zItem in _ListData)
    {
        <div class="form-group row mb-0" key="@zItem.CategoryKey">
            <div class="col-12">
                <div class="input-group">
                    <input type="text" class="form-control rounded-0" placeholder="" key="@zItem.CategoryKey" value="@zItem.CategoryNameVN" />
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-primary rounded-0"
                                onclick="Save(@zItem.CategoryKey)">
                            <i class="far fa-save"></i>
                        </button>
                        <button type="button" class="btn btn-outline-danger rounded-0"
                                onclick="Delete(@zItem.CategoryKey)">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script>
        var URL_Save = "@Url.Action("SaveCategoryProduct", "Mobile")";
        var URL_Delete = "@Url.Action("DeleteProductCategory", "Mobile")";
        var height = $(window).height() - 350;

        $(document).ready(function () {
            $(".header").remove();
        });

        function Delete(Key) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: 'POST',
                                data: {
                                    "CategoryKey": Key,
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.Success) {
                                        $("div[key=\"" + Key + "\"]")
                                            .css({ 'background': 'red', 'color': 'white' })
                                            .fadeOut(500, function () { $(this).remove(); });
                                    }
                                    else {
                                        alert(r.Message);
                                    }
                                },
                                error: function (err) {
                                    console.log(err.responseText);
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }
        function Save(Key) {
            var name = 'Nội dung mới';
            if (Key != 0)
            {
                name = $("input[key=" + Key + "]").val();
            }
            $.ajax({
                url: URL_Save,
                type: 'POST',
                data: {
                    "CategoryKey": Key,
                    "CategoryName": name,
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        alert(r.Message);
                    }
                },
                error: function (err) {
                    console.log(err.responseText);
                },
                complete: function () {

                }
            });
        }
    </script>
}

Views/Mobile/Config/CategoryReceipt.cshtml
@{
    ViewBag.Title = "CategoryReceipt";
    Layout = "~/Views/Shared/_Layout_mHome.cshtml";
    List<CashReceipt_Category_Model> _ListData = new List<CashReceipt_Category_Model>();
    if (ViewBag.List != null)
    {
        _ListData = ViewBag.List as List<CashReceipt_Category_Model>;
    }
}
<div class="row m-0 border border-top bg-white pageHead">
    <div class="col-md-12 p-0">
        <table class="table table-borderd">
            <tr>
                <td class="text-center" style="vertical-align: middle; width:15%" onclick="Utils.BackWithRefresh()">
                    <a href="@Url.RouteUrl("mCaiDat")">
                        <i class="fas fa-2x fa-angle-left"></i>
                    </a>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <h4>Danh mục thu phí</h4>
                </td>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a href="#" onclick="Save(0)">
                        <i class="fas fa-2x fa-plus"></i>
                    </a>
                </td>
            </tr>
        </table>

    </div>
</div>

<div class="bg-white" style="padding-top:72px !important;">
    @foreach (CashReceipt_Category_Model zItem in _ListData)
    {
        <div class="form-group row mb-0" key="@zItem.CategoryKey">
            <div class="col-12">
                <div class="input-group">
                    <input type="text" class="form-control rounded-0" placeholder="" key="@zItem.CategoryKey" value="@zItem.CategoryNameVN" />
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-primary rounded-0"
                                onclick="Save(@zItem.CategoryKey)">
                            <i class="far fa-save"></i>
                        </button>
                        <button type="button" class="btn btn-outline-danger rounded-0"
                                onclick="Delete(@zItem.CategoryKey)">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


@section Scripts{
    <script>
        var URL_Save = "@Url.Action("SaveCategory", "Mobile")";
        var URL_Delete = "@Url.Action("DeleteCategory", "Mobile")";
        var height = $(window).height() - 350;

        $(document).ready(function () {
            $(".header").remove();            
        });
        function Delete(Key) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: 'POST',
                                data: {
                                    "CategoryKey": Key,
                                    "Type": "Receipt"
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.Success) {
                                        $("div[key=\"" + Key + "\"]")
                                            .css({ 'background': 'red', 'color': 'white' })
                                            .fadeOut(500, function () { $(this).remove(); });
                                        return false;
                                    }
                                    else {
                                        alert(r.Message);
                                    }
                                },
                                error: function (err) {
                                    console.log(err.responseText);
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }        
        function Save(Key) {
            var name = 'Nội dung mới';
            if (Key != 0)
            {
                name = $("input[key=" + Key + "]").val();
            }
            $.ajax({
                url: URL_Save,
                type: 'POST',
                data: {
                   "CategoryKey": Key,
                   "CategoryName": name,
                   "Type": "Receipt"
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        alert(r.Message);
                    }
                },
                error: function (err) {
                    console.log(err.responseText);
                },
                complete: function () {

                }
            });
        }
    </script>
}