Models/Customer/Customer_Data.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
namespace TNStores
{
    public class Customer_Data
    {
        public static List<Customer_Model> List(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = "SELECT * FROM CRM_Customer WHERE RecordStatus != 99 AND PartnerNumber = @PartnerNumber ORDER BY CustomerID DESC";
            string zConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Customer_Model> zList = new List<Customer_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Customer_Model()
                {
                    CustomerKey = r["CustomerKey"].ToString(),
                    CustomerID = r["CustomerID"].ToString(),
                    FullName = r["FullName"].ToString(),
                    CompanyName = r["CompanyName"].ToString(),
                    Aliases = r["Aliases"].ToString(),
                    JobTitle = r["JobTitle"].ToString(),
                    CategoryKey = r["CategoryKey"].ToInt(),
                    CategoryName = r["CategoryName"].ToString(),
                    CustomerType = r["CustomerType"].ToInt(),
                    CustomerTypeName = r["CustomerTypeName"].ToString(),
                    CustomerVendor = r["CustomerVendor"].ToInt(),
                    TaxNumber = r["TaxNumber"].ToString(),
                    IDCard = r["IDCard"].ToString(),
                    Address = r["Address"].ToString(),
                    City = r["City"].ToString(),
                    Country = r["Country"].ToString(),
                    ZipCode = r["ZipCode"].ToString(),
                    Phone = r["Phone"].ToString(),
                    Email = r["Email"].ToString(),
                    Note = r["Note"].ToString(),
                    Style = r["Style"].ToString(),
                    Class = r["Class"].ToString(),
                    CodeLine = r["CodeLine"].ToString(),
                    BankAccount = r["BankAccount"].ToString(),
                    BankName = r["BankName"].ToString(),
                    Referrer = r["Referrer"].ToString(),
                    Password = r["Password"].ToString(),
                    Parent = r["Parent"].ToString(),
                    Slug = r["Slug"].ToInt(),
                    PartnerNumber = r["PartnerNumber"].ToString(),
                    Contact = r["Contact"].ToString(),
                    RecordStatus = r["RecordStatus"].ToInt(),
                    CreatedOn = (r["CreatedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["CreatedOn"]),
                    CreatedBy = r["CreatedBy"].ToString(),
                    CreatedName = r["CreatedName"].ToString(),
                    ModifiedOn = (r["ModifiedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["ModifiedOn"]),
                    ModifiedBy = r["ModifiedBy"].ToString(),
                    ModifiedName = r["ModifiedName"].ToString(),
                });
            }
            return zList;
        }
    }
}

Controllers/DesktopController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace TNStores.Controllers
{
    public class DesktopController : BaseController
    {
        // GET: Desktop
        public ActionResult Index()
        {
            return View();
        }

        #region [CUSTOMER]
        public ActionResult ListCustomer()
        {
            ViewBag.ListData = Customer_Data.List(UserLog.PartnerNumber, out string Message);
            return View("~/Views/Desktop/Customer/List.cshtml");
        }

        [HttpGet]
        public JsonResult DetailCustomer(string CustomerKey)
        {
            ServerResult zResult = new ServerResult();
            Customer_Info zInfo = new Customer_Info(CustomerKey);
            Customer_Model zModel = zInfo.Customer;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult UpdateCustomer(string CustomerKey = "", string TaxNumber = "", string Phone = "", string FullName = "", string Address = "", string Description = "")
        {
            Customer_Model zModel = new Customer_Model();
            zModel.CustomerKey = CustomerKey;
            zModel.TaxNumber = TaxNumber;
            zModel.Phone = Phone;
            zModel.Address = Address;
            zModel.FullName = FullName;
            zModel.Note = Description;
            zModel.PartnerNumber = UserLog.PartnerNumber;
            zModel.CreatedBy = UserLog.UserKey;
            zModel.CreatedName = UserLog.EmployeeName;
            zModel.ModifiedBy = UserLog.UserKey;
            zModel.ModifiedName = UserLog.EmployeeName;

            Customer_Info zInfo = new Customer_Info(CustomerKey);
            zInfo.Customer = zModel.TrimStringProperties();
            if (CustomerKey.Length >= 36)
            {
                zInfo.Update();
            }
            else
            {
                zInfo.Create_ServerKey();
            }

            ServerResult zResult = new ServerResult();
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult DeleteCustomer(string CustomerKey)
        {
            ServerResult zResult = new ServerResult();
            Customer_Info zInfo = new Customer_Info();
            zInfo.Customer.CustomerKey = CustomerKey;
            zInfo.Delete();
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
                return Json(zResult, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region [PurchaseOrder]
        public ActionResult PurchaseOrderEdit(string Key)
        {
            return View("~/Views/Desktop/PO/PurchaseEdit.cshtml");
        }

        private string Customer_PurchaseOrder(string Key, string Phone, string Name, string Address, string Tax, int isVendor, out string Message)
        {
            string CustomerKey = Guid.NewGuid().ToString();
            Customer_Info zInfo = new Customer_Info();
            if (Key.Length == 0 &&
                Phone.Length > 0 &&
                Name.Length > 0)
            {
                zInfo.Customer.FullName = Name;
                zInfo.Customer.Phone = Phone;
                zInfo.Customer.Address = Address;
                zInfo.Customer.CustomerKey = CustomerKey;
                zInfo.Customer.PartnerNumber = UserLog.PartnerNumber;
                zInfo.Customer.CreatedBy = UserLog.UserKey;
                zInfo.Customer.CreatedName = UserLog.EmployeeName;
                zInfo.Customer.ModifiedBy = UserLog.UserKey;
                zInfo.Customer.ModifiedName = UserLog.EmployeeName;
                zInfo.Create_ClientKey();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                Message = string.Empty;
            }
            else
            {
                CustomerKey = Key;
                Message = zInfo.Message;
            }
            return CustomerKey;
        }
        private void Payment_PurchaseOrder(string OrderID, double Amount, string CustomerKey, string Name, string Phone, out string Message)
        {
            Payment_Model zPayment = new Payment_Model();
            zPayment.PartnerNumber = UserLog.PartnerNumber;
            zPayment.CreatedBy = UserLog.UserKey;
            zPayment.CreatedName = UserLog.EmployeeName;
            zPayment.ModifiedBy = UserLog.UserKey;
            zPayment.ModifiedName = UserLog.EmployeeName;
            zPayment.DocumentID = OrderID;
            zPayment.PaymentID = Payment_Data.Auto_Payment_ID(UserLog.PartnerNumber);
            zPayment.PaymentDate = DateTime.Now;
            zPayment.PaymentDescription = "Chi đơn nhâp, mua hàng [" + OrderID + "] tự động !.";
            zPayment.AmountCurrencyMain = Amount;
            zPayment.Slug = 9;
            zPayment.CustomerKey = CustomerKey;
            zPayment.CustomerName = Name;
            zPayment.CustomerPhone = Phone;
            zPayment.CategoryKey = 12;
            zPayment.CategoryName = "Chi mua nhập hàng";

            Payment_Info zInfo = new Payment_Info();
            zInfo.Payment = zPayment;
            zInfo.Create_ServerKey();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                Message = string.Empty;
            }
            else
            {
                Message = zInfo.Message;
            }
        }
        private void Save_PurchaseOrderItem(List<Input_Product_Model> ListItem, string OrderKey, out string Message)
        {
            Message = string.Empty;
            for (int i = 0; i < ListItem.Count; i++)
            {
                Input_Product_Info zItemInfo = new Input_Product_Info();
                zItemInfo.Input_Product = ListItem[i];
                zItemInfo.Input_Product.OrderKey = OrderKey;
                zItemInfo.Input_Product.PartnerNumber = UserLog.PartnerNumber;
                zItemInfo.Input_Product.CreatedBy = UserLog.UserKey;
                zItemInfo.Input_Product.CreatedName = UserLog.EmployeeName;
                zItemInfo.Input_Product.ModifiedBy = UserLog.UserKey;
                zItemInfo.Input_Product.ModifiedName = UserLog.EmployeeName;
                zItemInfo.Create_ServerKey();

                if (zItemInfo.Code != "200" &&
                    zItemInfo.Code != "201")
                {
                    Message = zItemInfo.Message;
                    return;
                }
            }
        }
        private void Update_PurchaseStockItem(List<Input_Product_Model> ListItem, string Orderkey, string OrderID, out string Message)
        {
            string SQL = "";
            for (int i = 0; i < ListItem.Count; i++)
            {
                string ProductKey = ListItem[i].ProductKey;
                float QuantityFact = ListItem[i].QuantityFact;
                string QuantityLog = DateTime.Now + ";IN;" + Orderkey + ";" + OrderID + ";" + QuantityFact + Environment.NewLine;

                SQL += "UPDATE PDT_Product SET QuantityFact = QuantityFact + " + QuantityFact + ", QuantityLog = ISNULL(QuantityLog, '') + N'" + QuantityLog + "' WHERE RecordStatus <> 99 AND ProductKey = '" + ProductKey + "'";
            }

            Helper.RunSQL(SQL, out Message);
        }

        [HttpPost]
        public JsonResult Save_PurchaseOrder(string Info, string Method = "Pay")
        {
            ServerResult zResult = new ServerResult();
            Input_Order_Model zOrderClient = JsonConvert.DeserializeObject<Input_Order_Model>(Info);
            double RealAmount = 0;
            string OrderKey = Guid.NewGuid().ToString();
            string OrderID = Helper.AutoID_PurchaseOrder(UserLog.PartnerNumber, "PO");
            string Message = "";
            try
            {
                Input_Order_Model zOrderModel = (Input_Order_Model)Session["PurchaseOrder"];

                if (zOrderModel != null && zOrderModel.ListItem.Count > 0)
                {
                    #region [Khách hàng]
                    string CustomerKey = Customer_PurchaseOrder(zOrderClient.VendorKey, zOrderClient.VendorPhone, zOrderClient.VendorName, zOrderClient.VendorAddress, string.Empty, 0, out Message);
                    if (Message.Length > 0)
                    {
                        zResult.Success = false;
                        zResult.Message = Message;
                        return Json(zResult, JsonRequestBehavior.AllowGet);
                    }
                    #endregion

                    #region [Đơn hàng]                   
                    RealAmount = zOrderClient.AmountOrder - zOrderClient.AmountDiscount;

                    zOrderModel.DocumentOrigin = zOrderClient.DocumentOrigin;

Views/Desktop/Customer/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout_Desktop.cshtml";
    List<Customer_Model> _ListData = new List<Customer_Model>();
    if (ViewBag.ListData != null)
    {
        _ListData = ViewBag.ListData as List<Customer_Model>;
    }
}

<header class="page-header">
    <h2>Khách hàng</h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="@Url.Action("Index","Home")">
                    <i class="fas fa-home"></i>
                    Trang chủ
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
<div class="row">
    <div class="col-md-12">
        <div class="card border border-primary">
            <div class="card-header border-primary">

            </div>
            <div class="card-body border-primary p-0" id="divTable">
                <table class="table Custom table-sm" id="tblData" style="min-width:max-content">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>SĐT</th>
                            <th>MST</th>
                            <th>Họ và tên</th>
                            <th>Địa chỉ</th>
                            <th>Ghi chú</th>
                            <th class="text-right">
                                <button class="modal-with-zoom-anim btn btn-info" type="button" onclick="Detail(0)">
                                    <i class="fa fa-plus"></i>
                                    Thêm mới
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tblBody">
                        @for (int i = 0; i < _ListData.Count; i++)
                        {
                            Customer_Model Model = _ListData[i];
                            <tr key="@Model.CustomerKey">
                                <td>@(i + 1)</td>
                                <td>@Model.Phone</td>
                                <td>@Model.TaxNumber</td>
                                <td>@Model.FullName</td>
                                <td>@Model.Address</td>
                                <td>@Model.Note</td>
                                <td class="text-right">
                                    <button type="button" class="btn btn-outline-primary btn-sm modal-with-zoom-anim" onclick="Detail('@Model.CustomerKey')">
                                        <i class="far fa-edit"></i>
                                    </button>
                                    <button type="button" class="btn btn-outline-danger btn-sm modal-with-zoom-anim" onclick="Delete('@Model.CustomerKey')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer border-primary">
            </div>
        </div>
    </div>
</div>
<div id="modalEdit" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
    <div class="card border border-primary">
        <div class="card-header">
            <h2 class="card-title">Thông tin khách hàng</h2>
        </div>
        <div class="card-body border-primary">
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-right">Số điện thoại</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_Phone" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-right">Mã số thuế</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_TaxNumber" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-right">Họ tên</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_FullName" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-right">Địa chỉ</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_Address" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-right">Ghi chú</label>
                <div class="col-lg-7 col-xl-9">
                    <textarea class="form-control" id="txt_Description" placeholder="" required=""></textarea>
                </div>
            </div>
        </div>
        <div class="card-footer border-primary text-center">
            <button id="btn_Cancel" type="button" class="btn btn-outline-secondary modal-dismiss">
                <i class="far fa-times-circle"></i>
                Đóng
            </button>
            <button id="btn_Save" type="button" class="btn btn-outline-primary" onclick="Save()">
                <i class="far fa-save"></i>
                Cập nhật
            </button>
        </div>
    </div>
    <input id="txt_CustomerKey" type="hidden" name="Role" value="" />
</div>
@section scripts{
    <script src="~/Assets/App_JS/3rt/tableHeadFixer.js"></script>
    <script>
        var URL_Detail = "@Url.Action("DetailCustomer", "Desktop")";
        var URL_Delete = "@Url.Action("DeleteCustomer", "Desktop")";
        var URL_Save = "@Url.Action("UpdateCustomer", "Desktop")";
    </script>
    <script>
        $(document).ready(function () {
            $("#divTable").css({
                "height": $(window).height() - 290,
            });
            $("#tblData").tableHeadFixer({
                head: true,
                foot: false,
                left: 2,
                right: 1,
                "z-index": "501"
            });
        });
        function Save() {
            var CustomerKey = $("#txt_CustomerKey").val();
            var Phone = $("#txt_Phone").val();
            var FullName = $("#txt_FullName").val();
            var Address = $("#txt_Address").val();
            var Description = $("#txt_Description").val();
            var TaxNumber = $("#txt_TaxNumber").val();
            $.ajax({
                url: URL_Save,
                type: "POST",
                data: {
                    "CustomerKey": CustomerKey,
                    "Phone": Phone,
                    "FullName": FullName,
                    "Address": Address,
                    "Description": Description,
                    "TaxNumber": TaxNumber
                },
                beforeSend: function () {
                    Utils.LoadIn();
                },
                success: function (r) {
                    if (r.Success) {
                        location.reload();
                    }
                    else {
                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                    }
                },
                error: function (err) {
                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                },
                complete: function () {

                }
            });
        }
        function Detail(CustomerKey) {
            Utils.OpenMagnific("#modalEdit");
            if (CustomerKey.length >= 36) {
                $.ajax({
                    url: URL_Detail,
                    type: "GET",
                    data: {
                        "CustomerKey": CustomerKey
                    },
                    beforeSend: function () {

                    },
                    success: function (r) {
                        if (r.Success) {
                            var obj = JSON.parse(r.Data);

                            $("#txt_CustomerKey").val(obj.CustomerKey);
                            $("#txt_Phone").val(obj.Phone);
                            $("#txt_FullName").val(obj.FullName);
                            $("#txt_Address").val(obj.Address);
                            $("#txt_Description").val(obj.Note);
                            $("#txt_TaxNumber").val(obj.TaxNumber);
                        }
                        else {
                            Utils.OpenNotify(r.Message, "Thông báo", "error");
                        }
                    },
                    error: function (err) {
                        Utils.OpenNotify(err.responseText, "Thông báo", "error");
                    },
                    complete: function () {

                    }
                });
            }
            else {
                Utils.ClearUI("#modalEdit");
                $("#rdo1").val(1);
                $("#rdo0").val(0);

                $.ajax({
                    url: URL_AutoID,
                    type: "GET",
                    data: {

                    },
                    beforeSend: function () {

                    },
                    success: function (r) {
                        $("#txt_EmployeeID").val(r);
                    },
                    error: function (err) {
                        Utils.OpenNotify(err.responseText, "Thông báo", "error");
                    },
                    complete: function () {

                    }
                });
            }
        }
        function Delete(CustomerKey) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: "POST",
                                data: {
                                    "CustomerKey": CustomerKey
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.Success) {
                                        $("tr[key=\"" + CustomerKey + "\"]").remove();
                                    }
                                    else {
                                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }

    </script>
}